% -------------------------------------------------------------------
%  Generated by MATLAB on 24-Apr-2026 10:58:33
%  MATLAB version: 25.2.0.3150157 (R2025b) Update 4
% ===================================================== 
%  UTS Matematika Sains Data — Semester Genap 2025/2026 
%  Soal 5 — Konvergensi Customer Lifetime Value dan Kekontinuan Biaya
%  --------------------------------------------------- 
%  Nama  : Abimanyu Daffa Saputra 
%  NIM   : 2510514032
%  Parameter: N=32, a=3, b=2, K=6, theta0=100, alpha=0,003 
%  Tanggal: <2026-4-24>
% -------------------------------------------------------------------
saveVarsMat = load('soal_5_limit_kontinuan.mat');

K = 6;

L1 = saveVarsMat.L1; % <1x1 sym> unsupported class

L2 = saveVarsMat.L2; % <1x1 sym> unsupported class

L3 = saveVarsMat.L3; % <1x1 sym> unsupported class

a = 3;

b = 2;

f1 = saveVarsMat.f1; % <1x1 function_handle> unsupported class

f2 = saveVarsMat.f2; % <1x1 function_handle> unsupported class

q = -6;

x = saveVarsMat.x; % <1x1 sym> unsupported class

clear saveVarsMat;
